### ISSUE TITLE
php-cgi

### ISSUE THREAD

**Issue by ichynul** [rabbitLove520/WinWnmp#22]
https://github.com/salamander-mh/SalamanderWnmp/blob/b0bef14d27556f3e05a9cbb63ae0e8afdb07fd1e/SalamanderWnmp/Programs/PHP.cs#L10
这里能加个前缀就好了，因为系统里面可能同时用多套组合，比如IIS会有php-cgi.exe进程存在

**Comment by salamander-mh** [comment]
这个的话，进程有自己的一些信息的，可以看出执行位置是哪里的

**Comment by ichynul** [comment]
我在服务器上用，启动以后php没起来，面板上显示php是启动状态的。估计是IIS启动的的php进程。在面板把拍php关了在启动nginx的网站才可以访问。我就是觉得是不是因为这个进程名"php-cgi"跟其他启动的同名导致。
